getethos/ethos-design-system

- src/KitchenSink.js
- src/components/Inputs/ZipInput/ZipInput.js
- src/components/Inputs/ZipInput/ZipInput.md
- src/components/Inputs/ZipInput/ZipInput.test.js
- src/components/Inputs/ZipInput/ZipInputValidator.js
- src/components/Inputs/ZipInput/ZipInputValidator.test.js
- src/components/Inputs/ZipInput/index.js
- src/components/index.js
Removes onValidation. Now, per our discussion, we'll take a validator prop which gives the caller visibility. Also, we move the boiler-plate validator into corresponding external file; caller is expected to use that or provide their own validation (or both if they choose to wrap the boilerplate)
> boilerplate validation

- src/KitchenSink.js
- src/components/Button/Button.js
- src/components/Button/Button.scss
- src/components/Button/Button.test.js
- src/components/Button/__snapshots__/Button.test.js.snap
- src/components/ButtonSelectGroup/ButtonSelectGroup.js
- src/components/ButtonSelectGroup/ButtonSelectGroup.md
- src/components/ButtonSelectGroup/ButtonSelectGroup.test.js
- src/components/ButtonSelectGroup/OptionButton.js
- src/components/ButtonSelectGroup/__snapshots__/ButtonSelectGroup.test.js.snap
- src/components/ButtonSelectGroup/index.js
- src/components/design-system.css
Adding the ability to set the `<Options />` in a `<ButtonSelectGroup />` to `White`
- Added the ability to style `<ButtonSelectGroup />` `<Option />` buttons through the use of a style `Enum`
- Added new test cases
> Adding buttonStyles to ButtonSelectGroup

- styleguide/content/color/color.scss
Import CSS File Case Sensitive fix
By default, MacOS does not have case sensitivity for files. And that was the reason I wasn't have been able to build this locally.
If you want a case sensitive volume: https://coderwall.com/p/mgi8ja/case-sensitive-git-in-mac-os-x-like-a-pro
> Case Sensitive File Fix

- README.md
People can't run `yarn styleguide` if they haven't installed the fonts. This documents what they need to do more fully.
> Add font info to README

- README.md
- Just noticed we switched ports to 9008, when we run locally.
- Styleguide config port number set: https://github.com/getethos/ethos-design-system/blob/7becd7ece14f08e1db606ddef612e0cf957d008d/styleguide.config.js#L31
> Update README port url

- src/components/UniversalNavbar/UniversalNavbar.js
- There was one other place where `/login` is being used and is supposed to be a link.
- Fix proptypes warnings due to `expected a ReactNode`. https://github.com/facebook/react/issues/5527
> Account link and fix proptypes warnings

- src/components/Media/Media.md
Premptive deprecation warning so folks stop using the Media.js React component:
> Loud deprecation notice for Media component

- src/components/Inputs/ButtonSelectGroup/ButtonSelectGroup.js
- src/components/Inputs/ButtonSelectGroup/__snapshots__/ButtonSelectGroup.test.js.snap
We found one more case of incorrect `allCaps` being `false`. This is for: https://github.com/getethos/cms/pull/1958
> another all caps false that should be true

- src/components/Inputs/ButtonSelectGroup/ButtonGroup.module.scss
- src/components/Inputs/ButtonSelectGroup/ButtonSelectGroup.js
- src/components/Inputs/ButtonSelectGroup/ButtonSelectGroup.md
- src/components/Inputs/ButtonSelectGroup/__snapshots__/ButtonSelectGroup.test.js.snap
Needed for unum forms
Defaults to true so existing button groups should be unaffected.
> ButtonSelectGroup now has a fullWidth prop, defaults to true

- src/components/Inputs/BirthdateInput/BirthdateInput.js
- src/components/Inputs/CheckboxInput/CheckboxInput.js
- src/components/Inputs/NumberInput/NumberInput.md
- src/components/Inputs/TextInput/TextInput.js
- src/components/Inputs/TextMaskedInput/TextMaskedInput.js
- src/components/Inputs/ZipInput/ZipInput.js
- src/components/index.js
- src/hooks/useErrorMessage.js
- [Asana Task](https://app.asana.com/0/1136962714401929/1145702600849513/f)
- Form touch refactor
___
Looks like "field touch" or, field blur is what should determine whether field level error messages are displayed or not. 
If you look at this vanilla Formik example, we can see the default is field touch:
https://jasonwatmore.com/post/2019/04/10/react-formik-form-validation-example
Here’s an example from Jared himself (the author), and his description implies how Formik defaults to touch-based error message visibility:
> A Formik form where errors are shown while the user types (**instead of showing after blur event**). Submission is also prevented if there are any errors.
Note his example requires the application developer to override the default functionality. It also …
> Unum form touch issue

- src/components/RadioButtons/RadioButtons.js
Styleguide can work surprisingly well despite missing imports. I have made this mistake quite a few times, forgetting to export a new component from src/components/index.js for example. EDS team might want to look into this
> Fix import in radio buttons

- package.json
- src/components/Inputs/ButtonSelectGroup/ButtonSelectGroup.js
hotfix issue in cms
Here's local and it preserves ability to use `false` as initial value
> hotfix for prevalidation issue in cms

- package.json
- src/components/Type/Link.js
- src/components/Type/Link.module.scss
- src/components/Type/Type.scss
- src/components/design-system.css
- stats.json
- [Asana Task](https://app.asana.com/0/1136962714401929/1143741730422930)
- Removes Link-related globals from the CSS bundle (which shrinks 5%).
- No major issues found in CMS yet so I think this is good for final CR.
- Gonna do one last quick round of CMS QA and then I'll be ready to merge.
- https://github.com/getethos/cms/pull/1997
- See https://github.com/getethos/cms/pull/1997.
> Move Link to CSS modules

- src/components/Button/Button.module.scss
Full Width Buttons on a phone viewport is not full width when it is limited with `max-width` property
> Remove Max-width on fullWidth buttons

- package.json
The node engine requirement would require monorepo et al to upgrade node. It seems like eslint runs fine with 10.6 so this PR downgrades to match what we have across our stack.
- https://github.com/getethos/ethos-design-system/pull/104/files
`yarn lint` runs fine. We have a lot to fix apparently, but that should be done on a follow up branch I think since it's not blocking our consumers as the node engine thing IS.
> Downgrading

- src/components/Button/Button.module.scss
- src/components/Inputs/ButtonSelectGroup/ButtonGroup.module.scss
- src/components/Inputs/CheckboxInput/CheckboxInput.module.scss
- src/components/Inputs/Errors.module.scss
- src/components/Inputs/TextInput/TextInput.module.scss
- src/components/Layout/Layout.module.scss
- src/components/RadioButtons/RadioButtons.module.scss
- src/components/Type/Link.module.scss
- src/components/Type/Type.module.scss
- src/components/UniversalNavbar/TransformingBurgerButton/TransformingBurgerButton.module.scss
- [Asana Task](https://app.asana.com/0/1136962714401929/1146699554558697/f)
- Fix EDS composes / css modules when consumed by monorepo
Note I elected to only convert comments in .module.scss files since those will be the only ones we do `composes: ` from. It's weird that .scss files get evaluated by postcss-loader before css-loader, but everywhere on the web recommends this ordering.
tried from monorepo pointed here for all envs:
- https://github.com/getethos/ethos/pull/1451
> Fix EDS composes / css modules when consumed by monorepo

- src/components/Form/FormPrefilled.js
- src/components/Form/FormPrefilled.md
- src/components/Inputs/BirthdateInput/BirthdateInput.js
- src/components/Inputs/CheckboxInput/CheckboxInput.js
- src/components/Inputs/TextAreaInput/TextAreaInput.js
- src/components/Inputs/TextInput/TextInput.js
- src/components/Inputs/TextMaskedInput/TextMaskedInput.js
- src/components/Inputs/ZipInput/ZipInput.js
- [Asana Task](https://app.asana.com/0/1136962714401929/1146473861245233/f)
- Questions Page - Continue disabled with all inputs prefilled
Essentially, `initialValue` for a given field will now result:
1. field is considered _touched_
2. the field's validation will get called. This means the form state is a aware of the field's validity
If the initial values are valid values and all for fields are using this, the `buttonIsValid()` will return true and thus the submit button will show as enabled.
** Notes: **
To verify interact with http://localhost:9008/#/Components/FormPrefilled and try manually setting the `initialValue` for the fields to invalid values and watch that the submit button gets disabled.
> Prefill still requires touching fields

- package.json
- scss-test.sh
Prevent monorepo breaking in stage/prod environments due to postcss dying on `//` comment syntax in `.module.scss` files. Followup to https://github.com/getethos/ethos-design-system/pull/116
> SCSS test to prevent comment style which breaks monorepo

- src/components/Form/Form.js
- src/components/Form/Form.md
- src/hooks/useFormState.js
- [Asana Task](https://app.asana.com/0/1136962714401929/1146709581895113/f)
-  hide becomes markHidden since we do not hide the thing but mark it as hidden thus do not consider when returning for values or validating fields for errors etc.
This is a temporary page I created...but I marked buttonGroup 2 and 3 as hidden after clicking the 'Yo' button...the console.log shows that we only returned button 1 in the  form state collection
> hide becomes markHidden

- src/components/Inputs/BirthdateInput/__snapshots__/BirthdateInput.test.js.snap
- src/components/Inputs/ButtonSelectGroup/__snapshots__/ButtonSelectGroup.test.js.snap
- src/components/Inputs/EmailInput/__snapshots__/EmailInput.test.js.snap
- src/components/Inputs/NumberInput/__snapshots__/NumberInput.test.js.snap
- src/components/Inputs/PasswordInput/__snapshots__/PasswordInput.test.js.snap
- src/components/Inputs/TextAreaInput/__snapshots__/TextAreaInput.test.js.snap
- src/components/Inputs/TextInput/__snapshots__/TextInput.test.js.snap
- src/components/Inputs/ZipInput/__snapshots__/ZipInput.test.js.snap
- src/components/Spacer/Spacer.js
- src/components/Spacer/Spacer.test.js
- src/components/Spacer/__snapshots__/Spacer.test.js.snap
- [Asana Task](https://app.asana.com/0/1128987846241693/1117917027835300)
- Ideally we do spacing in CSS. To the extent that we use HTML we should be adding aria-hidden to hide the nonsemantic tags from screen readers.
- I added this elsewhere and realized we should add it here. It's a one-liner + tests.
> Add aria-hidden, tests to Spacer (a11y fix)

- .eslintrc.js
- .travis.yml
- package.json
- src/components/Spacer/Spacer.test.js
- src/components/Spacer/__snapshots__/Spacer.test.js.snap
- [Round 1](https://github.com/getethos/ethos-design-system/pull/126), [Round 2](https://github.com/getethos/ethos-design-system/pull/128)  
- This should prevent further lint errors by failing locally and in CI if you add more.
- The basic idea is, we have 82 issues, and if that goes up, the build fails. Later we reduce 82 to 0.
- TLDR: this doesn't fix everything we could possibly fix, but it prevents things from worsening.
**Notes:**
- The biggest source of remaining lint problems (30%) is propTypes in Form.js.
- The rest are propTypes elsewhere and `no-unused-vars`.
- The docs for --max-warnings: https://eslint.org/docs/user-guide/command-line-interface#exit-codes
Here is what it looks like when you add a new lint problem (unused variable `foo`):
> Cap lint problems

- src/hooks/useFormState.js
- src/hooks/useFormState.test.js
- src/hooks/useRequired.js
- [Asana Task](https://app.asana.com/0/1136962714401929/1146342193058673/f)
-     Remove unused variables in hooks causing linting warnings
Gets us down to 
✖ 55 problems (0 errors, 55 warnings)
> Remove unused variables in hooks causing linting warnings

- src/hooks/useErrorMessage.js
- [Asana Task](https://app.asana.com/0/1136962714401929/1147477344968945/f)
- Fix useErrorMessage when no validator
Fix issue when consumer does not supply a validator to a component (it is not required), we inject a noop one so we don't error out calling undefined.
_We'll do a part II to this and [remove calls to useErrorMessage](https://app.asana.com/0/1136962714401929/1147477344968947/f) if the component hasn't been provided a `validator` or similar_
> useErrorMessage when no validator

- src/components/Inputs/ButtonSelectGroup/ButtonSelectGroup.js
- src/components/Inputs/ButtonSelectGroup/OptionButton.js
Fixes warnings after https://github.com/getethos/ethos-design-system/pull/137 
I suppose this is a more lenient fix but was the only one that made the proptype errors go away. From logging things out from tests and console in chrome, it seems like sometimes it's an array but others it's an object. 
This also adds children prop type to OptionButton which seems related
> Fixes warnings on children being an object

- .travis.yml
- src/components/Form/Form.js
- [Asana Task](https://app.asana.com/0/1136962714401929/1146342193058673/f)
- Fixes prop type warning Form.js
> Form.js PropTypes fixes

- src/components/Button/Button.js
- src/components/Button/Button.md
- src/components/Button/Button.module.scss
Added scss rules so that the icons are the same color as the test in their button; also added some more examples and structure to the button.md styleguide page.
Old version where all arrow icons are white:
New:
> Add colors for arrowicons in buttons, and expand styleguide demos

- package.json
- scss-test.sh
Actually exits with error code, preventing monorepo webpack bugs. Rearranged test order so the faster thing happens first and also you can pass -u to yarn test.
> SCSS test successfully fails now 😅 also can pass -u to yarn test

- src/components/Images/Images.js
* Having alt as required was causing build issues when editors would make changes if they didn't have an alt. We can handle setting of alts as required on the CMS side and having it required in the DS is making things unnecessarily complicated.
> Remove required and add default for image alt

- package.json
- src/components/UniversalNavbar/UniversalNavbar.js
- src/components/UniversalNavbar/UniversalNavbar.md
- src/components/UniversalNavbar/__snapshots__/UniversalNavbar.test.js.snap
- Because the `UniversalNavbar` is used in the monorepo (`app.ethoslife.com`) and the CMS (`ethoslife.com`), having the logo route to `/` sends the user to different pages, depending on whether you're in the main app or CMS.
- This allows for passing in a parameter, `logoHref` to the component, so that we can send a user directly to `https://ethoslife.com/` rather than `href='/'`
> Update UniversalNavbar to accept logoHref parameters

- package.json
- src/components/Images/Images.js
If there is no src in an image tag and dataSrc is used only, there will be a brief flash of text on rerenders.
> Fix flash of alt text on SVG

- package.json
- src/xhr/src/XhrComponent.d.ts
- src/xhr/src/xhr.d.ts
Corresponding monorepo:
https://github.com/getethos/ethos/pull/1830
This is sort of a hotfix for issue caused as we did a first pass to [fix EDS typescript errors](https://github.com/getethos/ethos/commit/51d610e841af737bf202ae45bc6cfc54d61d74bc) which resulted in:
> Typescript noobs unite to suck together

- .gitignore
- src/components/Portal/Portal.js
- src/components/Portal/Portal.md
- src/components/Portal/Portal.test.js
- src/components/Portal/__snapshots__/Portal.test.js.snap
- src/components/Portal/index.js
- src/components/index.js
This PR adds the `<Portal />` component to the `EDS`. The `<Portal />` component.
The Portal component provides a way to create React portals dynamically. The component will create a new DOM node that attaches to the end of the document.body and render's the passed children within that DOM node.
This provides us a base for building Modals, Notifications, etc.
> Adding a `<Portal />` Component

- src/components/Form/Form.md
- src/components/Select/Select.js
- Supports this [Add DL edit functionality to user profiles in admin](https://app.asana.com/0/1149628124018183/1153703353529217)
- Validation for Forms was not hooked into our Select component. Also, labelCopy was not displayed like other form fields. This PR adds this stuff to Select. 
- For the future, it feels like we could use some sort of field wrapper to hold form-level logic as our components need a decent amount of form logic baked into them now. As you can see here, our simple Select component isn't so simple anymore. 
> Adds validation, errors, and field label to Select

- src/components/index.d.ts
- src/validators/validateExists.d.ts
This PR fixes issues testing pulling in latest v1.1.46 EDS into Nora...
Fixed in 6de837a9cc93af0fbce6cde68e451752805c59d1
Fixed in 70fb439d98f24b2a4a46af4a3ddfb60c2053e6f6 ... we needed to add `void` to the union type for `renderCallback`. Use case is we want to just set state with updated rows and have that trigger a re-render that picks up rendering the grid from another method:
```jsx
const renderCases = (rows: any) => {
if (!rows || !rows.length) {
return
}
/*** Here we are returning void but also updating state which will ultimately ***/
/*** kick in renderGrid method which renders the `JSX.Element | null` ***/
setRows(rows) 
}
const renderGrid = () => {
if (rows.length) {
return <LeGrid rows={rows} columns={columns} /> 
}
return null
}
return (
<>
{renderGrid()} …
```
> EDS / Nora Issues

- package.json
- src/components/Form/Form.md
- src/components/Select/Select.js
- After attempting to make our Select boxes work in our forms, I realized it's a bit more complex than I had  anticipated. These changes currently break any select box that use loadOptions instead of options. Rather than try to keep patching this, I'd rather revert, and really think about how to solve this problem. 
- Part of the complexity comes from react-select features that we use for the `AuraDeSearchField`, for example. When we use multi-select, we no longer have one selectedOption, we have an array of selectedOptions. We may pass in options or loadOptions and need to handle both. It's hard to touch the Select component and be confident that it works for all these cases. So more tests would also need to be written for me to feel secure changing this. 
- For the …
> Revert select box changes for form support

- package.json
- src/components/Grid/Grid.md
- src/components/Grid/Pagination.js
- src/components/Grid/Pagination.md
- src/components/Grid/Pagination.test.js
- [Asana Task](https://app.asana.com/0/1150068311310825/1155921313537887/f)
- Pagination should hide itself if items is <= number of items per page
- Data Grid column headers need to support `labelCopy` property
- https://github.com/getethos/ethos/pull/2012
Context: We noticed on the Nora side that if you only have a single page of results, the pagination arrow buttons still showed up which is a poor UX...
Consuming from Nora example with 6 items (1 page). Thing to note is the pagination is now completely hidden since there's only 1 page.
Nominal case (there are pages to paginate) still works:
Context on the issue: 
So we were using the `col.name` for both key and label which is of course silly 😋 …
> Conditionally paging buttons and add labelCopy prop to grid

- package.json
- src/components/Grid/Pagination.module.scss
- src/nora/components/Colors.css
- src/nora/components/Header/Header.module.scss
- src/nora/components/Tag/Tag.js
- src/nora/components/Tag/Tag.md
- src/nora/components/Tag/Tag.module.scss
- [Asana Task](https://app.asana.com/0/1150068311310825/1158041380837745)
- This PR adds Nora colors and also updates the `Tag` component to have all the colors we need. I decided to make the `Tag` component colors independent of status. In other words, the props we are passing are now colors e.g .`green` instead of `approved`.
- Tom and I worked on a color naming convention that would make sense for the Nora app. What we came up with is [here](https://www.figma.com/file/2Ulqfby7GNX8xU2yA2KeRW/%C2%B7%E2%80%80%E2%80%80%E2%80%80%E2%80%80%E2%80%80Nora%E2%80%80%E2%80%80%E2%80%80%E2%80%80%E2%80%80%C2%B7?node-id=790%3A122):
- 
> Nora colors and Tag additions

- src/nora/components/Tag/Tag.js
- src/nora/components/Tag/Tag.test.js
- src/nora/components/Tag/__snapshots__/Tag.test.js.snap
- [Asana Task](https://app.asana.com/0/1150068311310825/1158229807221425/f)
- Update the PropTypes for Nora Tag.js
- 
Before -- Nora dev tools show proptypes issue after we updated them [here](https://github.com/getethos/ethos-design-system/pull/231/files):
After pointing Nora to:
`    "ethos-design-system": "github:getethos/ethos-design-system#tag-types-followup",`
> Update Tag type PropTypes

- package.json
- src/components/Grid/useGridSorting.js
- src/components/index.d.ts
- [Ticket](https://app.asana.com/0/1150068311310825/1158253271849323)
- We aren't using the `compareBy` function when using the Grid in Nora because we have to re-fetch the page rather than sorting locally. 
- As a result, we need a way to set the sort state so that the correct sort icons appear.
- This PR adds the ability to set the sort state from outside of the EDS component.
- Tested locally to make sure that the sort still works and there are no console errors.
- https://github.com/getethos/ethos/pull/2046
> Add setSortState function for arrow control

- package.json
- src/components/Grid/useGridSorting.js
- src/components/Grid/useGridSorting.test.js
Why: There was no coverage for useGridSorting
How: Exposes a getSortDirection method and adds a spec
Tags: hooks, testing, grid, pagination
- [Asana Task](https://app.asana.com/0/1150068311310825/1157190385219569)
- Adds specs to the corresponding EDS changes that were merged yesterday and correspond to 2046 PR
- https://github.com/getethos/ethos/pull/2046/files
Consumed from Nora and was able to click the sort icons and it looked correct:
> Refactors useGridSorting and adds test coverage

- src/components/fa.js
- src/nora/components/IconLink/IconLink.md
- src/nora/components/IconLink/IconLink.module.scss
- [Asana Task](https://app.asana.com/0/1150068311310825/1160196321421673/f)
- This started as the back button chevron but turned into also fixing the black icon links
- Referencing from [Nora PR](https://github.com/getethos/ethos/pull/2207)
BEFORE (notice the link text is black not gray like the icon it's besides):
AFTER
> Nora chevron back button & fix black icon links

- package.json
- src/components/UniversalNavbar/UniversalNavbar.module.scss
- `blockNavbar` and NOT `blockNavBar`
- 
> Navbar spelling error

- package.json
- src/components/UniversalNavbar/FancyAnimatedLogo.scss
- src/components/UniversalNavbar/TransformingBurgerButton/TransformingBurgerButton.js
- src/components/UniversalNavbar/UniversalNavbar.js
- src/components/UniversalNavbar/UniversalNavbar.module.scss
- src/components/UniversalNavbar/__snapshots__/UniversalNavbar.test.js.snap
- src/components/design-system.css
- stats.json
[WIP] Until following CMS PR / todos complete. Otherwise it's ready from a code perspective & has been QA'd by design. (02/04/2020)
**Todo**
- Note this component will be overhauled very soon with the work in this [ticket](https://app.asana.com/0/1116481661798430/1158569544825133/f), so I'm hoping to push these smaller changes through quickly so we can get the initial help center work live in CMS
- [Asana Task](https://app.asana.com/0/1116481661798430/1142541556943565/f)
- Adds search icon linked to `/faq/`
- Replaced Account text link with account icon for `/login/`
- Tweaked `FancyAnimatedLogo` to fit with new search icon on mobile
- Changes old `FAQ` text link to `Blog` (`/faq/` -> `/blog/`)
- Design is choosing to use custom icons over FontAwesome for these changes
- …
> UniversalNavbar search/account icons + minor restyle

- package.json
- src/components/UniversalNavbar/UniversalNavbar.js
- src/components/UniversalNavbar/__snapshots__/UniversalNavbar.test.js.snap
- No related Asana task. 
- Recent updates to the `UniversalNavbar` changed the `FAQ` link to `Blog` and this PR reverts that change. There was some back and forth during development and since deployment went out this morning @justinsayarath has requested we revert to `FAQ`.
- Will coordinate with @iamvictorli to deploy this change on monorepo and CMS at the same time (Wednesday).
- n/a
> Change UniversalNavbar Blog (/blog/) link to FAQ (/faq/)

- package.json
- While I was working in EDS recently, I changed the input types for a component, but didn't realize that there was a corresponding test that I caused to fail. After realizing this in https://github.com/getethos/ethos-design-system/pull/268#issue-379281602, I thought I'd put up a PR to see whether people would be okay with adding `yarn test:types` to the pre-push hook.
- On my computer right now, `yarn test:types` takes about 6.5 seconds to run, while `yarn test` takes about 13.5.
- Below, I've validated that this hook works by purposely adding an incorrect type and validating that pre push hook throws an error.
- 
> Add yarn test:types to pre-push hook

- package.json
- src/components/Button/Button.js
- src/components/UniversalNavbar/FancyAnimatedLogo.scss
- src/components/UniversalNavbar/NavLink.js
- src/components/UniversalNavbar/UniversalNavbar.js
- src/components/UniversalNavbar/__snapshots__/UniversalNavbar.test.js.snap
- src/components/UniversalNavbar/assets/icons.js
- src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.js
- src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.md
- src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.module.scss
- src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.test.js
- src/components/UniversalNavbarExpanded/__snapshots__/UniversalNavbarExpanded.test.js.snap
- src/components/UniversalNavbarExpanded/constants.js
- src/components/design-system.css
- src/components/index.d.ts
- src/components/index.js
- Disclaimer: This work is a bit rushed so there is a lit of fast follow items documented at the bottom of the description which are being targeted for deployment Wednesday. They will increase the code quality and readability as well as address some minor design QA concerns. 
- Stakeholders are pushing to get this live in it's current state today (March 2nd). They've sat through a manual QA with me where we tested all the features on a CMS deploy preview.
- Mono should not be impacted until EDS version is bumped and even then nothing should visibly change.
- [Asana Task](https://app.asana.com/0/1116481661798430/1158569544825133/f)
- Adds `UniversalNavbarExpanded` for use on CMS in place of `UniversalNavbar`.
- The _very large diff deltas_ are explained in part by the new …
> UniversalNavbarExpanded

- src/components/index.d.ts
- Noticed this when consuming the `NoraDrawer` in the main app. 
- This is a simple fix and does NOT require a new release.
> Remove extra prop in NoraDrawer type definition

- src/components/UniversalNavbarExpanded/MobileNav/AccordionNav.js
- src/components/UniversalNavbarExpanded/MobileNav/MobileNav.js
- src/components/UniversalNavbarExpanded/MobileNav/SecondaryLinks.js
- src/components/UniversalNavbarExpanded/NavLink.js
- src/components/UniversalNavbarExpanded/SampleContent.js
- src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.js
- src/components/UniversalNavbarExpanded/__snapshots__/UniversalNavbarExpanded.test.js.snap
- src/helpers/preventCurrentPageNavigation.js
- src/helpers/preventCurrentPageNavigation.test.js
- Follow up to #279
- Renames some properties based on recent changes to helper name.
- Adds prop type comments to UniversalNavbarExpanded
> UniversalNavbarExpanded PropType comments & currentPage renames

- package.json
- Forgot to bump version for https://github.com/getethos/ethos-design-system/pull/275
-
> Bump verion to v1.1.119

- package.json
- setupCoreJsPollyfills.js
- src/components/Drawer/Drawer.js
- src/components/index.d.ts
- src/helpers/matches.js
- src/hooks/a11y/useOutsideClickIgnoreSelector.js
- src/hooks/a11y/useOutsideClickIgnoreSelectors.js
- src/hooks/a11y/useOutsideClickIgnoreSelectors.test.js
- src/nora/components/NoraDrawer/NoraDrawer.js
- src/nora/components/NoraDrawer/NoraDrawer.md
This adds the use outside click functionality including the floating action button (footer on the right side drawer) for https://github.com/getethos/ethos/pull/2528/files that was causing issues before the demo
> FloatingDrawerContentSelector prop for Drawers

- package.json
- src/components/fa.js
- Add rest of Nora icons according to icon sheet
- There are a few icons that are no longer needed, but since it's not quite clear what the game plan for minor UI updates to Nora is, I'm leaving them in for now (impact is minimal as we're doing deep imports).
-
> Add rest of nora icons

- package.json
- src/components/index.d.ts
- src/nora/components/IconLink/IconLink.js
- While working on the left sidebar, we discovered that we need to be able to pass down a data- attribute to icon links to differentiate them since they are not unique based off of text.
- In other words, we want to be able to avoid this:
- https://github.com/getethos/ethos/pull/2576
> Update IconLink to take in data-link-id

- package.json
- src/components/Grid/Grid.md
- src/components/Grid/Pagination.md
- src/components/Grid/useGridSorting.js
- src/components/fa.js
- [Asana Task](https://app.asana.com/0/1150068311310825/1168090685281633/f)
- Fix EDS react-icons (remove all usages)
_This was blocking some of Cole's Type work so it's sort of a hotfix_
Yes, `v1.1.150`
- Unblocks https://github.com/getethos/ethos/pull/2672/files
Not shown is _sort down_, but I verified it manually :)
> Remove react-icons usage and replaces with the same required fa icons

- package.json
- src/components/index.d.ts
- src/components/index.tests.tsx
- [Asana Task](https://app.asana.com/0/1150068311310825/1167333682122591/f)
- This will support the Nora application which needs to pull in Tooltips in a Typescript consumer. It looks like when we added the [Tooltip PR](https://github.com/getethos/ethos-design-system/pull/201) we neglected to add Typescript typings (and I approved it!); in reality I think we were just starting to introduce TS :)
This PR adds those typings
> Tooltip typing

- package.json
- src/components/Tooltip/Tooltip.js
- src/components/Tooltip/Tooltip.md
- src/components/Tooltip/Tooltip.module.scss
- src/components/Tooltip/TooltipExamples.module.scss
- src/components/index.d.ts
- [Asana Task](https://app.asana.com/0/0/1169062204585500/f)
- Refactor EDS Tooltip -- it's unclear how to opt out of the the information icons ('i' in circle) and we need to point to Nora's icon instead
https://github.com/getethos/ethos/pull/2752 will pull this in once ready
Adds a Children section to the example. After reading through the code I figured out that you can in fact override the information circle icon by just passing in children and wrapping with the tooltip tag. But, there were no examples of how to do so. Also, I needed a way to override the `PopperContent` box styles and so I:
- renamed `.contentBox` to `.popperContentBox` and had to put it at top level of CSS Module so we can …
> Tooltip Refactor for Customizability

- package.json
- src/components/index.d.ts
- src/nora/components/NoraRadioButtonGroup/NoraRadioButtonGroup.js
After bringing in https://github.com/getethos/ethos-design-system/pull/313 to Nora, and then testing in the form engine (modal is now in an EDS form engine), submit wasn't getting called because this component wasn't wired up correctly. I've explained more thoroughly in the screenshots section below...
_Note the nora radio component calls through to the underlying RadioButtonGroup component._
Without the proper props form engine doesn't get called (notice that `formChangeHandler` is undefined:
After adding these props, you can see the it's getting called now:
This allows the form to validate, so for example, in the test form below, you see that the submit button has been enabled. That only happens if the "form is valid" is true essentially:
> Nora radio followup

- package.json
- src/components/Grid/Column.module.scss
- src/components/Grid/grid-example.module.scss
This is just a follow up bugfix that I noticed on https://github.com/getethos/ethos/pull/2865 where I had duplicate props unintentionally
> Data grid hotfix

- README.md
- package.json
- src/components/Body.md
- src/components/Body2.js
- src/components/Body2.md
- src/components/Caption.md
- src/components/Caption2.js
- src/components/Caption2.md
- src/components/Footnote.md
- src/components/Type/TitleLarge.md
- src/components/Type/TitleMedium.md
- src/components/Type/TitleSmall.md
- src/components/Type/TitleXLarge.md
- src/components/Type/TitleXXLarge.md
- src/components/Type2/Blueprint.js
- src/components/Type2/TitleLarge2.js
- src/components/Type2/TitleLarge2.md
- src/components/Type2/TitleMedium2.js
- src/components/Type2/TitleMedium2.md
- src/components/Type2/TitleSmall2.js
- src/components/Type2/TitleSmall2.md
- src/components/Type2/TitleXLarge2.js
- src/components/Type2/TitleXLarge2.md
- src/components/Type2/index.js
- src/components/TypeBase/TypeBase.js
- src/components/TypeBase/TypeBase.module.scss
- src/components/index.d.ts
- src/components/index.js
**Todo**
- [Asana Task](https://app.asana.com/0/1116481661798430/1162971424036361/f)
- Adds the following components with their Type2 defined weights, font sizes, line heights and letter spacing.
- Body2
- Caption2
- TitleSmall2
- TitleMedium2
- TitleLarge2
- TitleXLarge2
- Open to discussing the Medium500/Book500 alias, see changes to README and Blueprint.js for context.
- I've asked Design if it's possible to get phone viewport mapping for the 7 `Not in use on Phone` cells in column D on the [spreadsheet here](https://docs.google.com/spreadsheets/d/1LiKYSuW5Lfh24OjT8e0WgNLcxuAZrFlbzmw_NJjUNOo/edit?usp=sharing). IMO it would be nice to have resizing fallbacks.
**Is this a new component? Please review these reminders:**
**Referencing PR or Branch (e.g. in CMS or …
> Type2 Transition - Phases 3/4

- package.json
- src/components/Portal/Portal.js
- Prevents `Portal` component from trying to reference `document` before it's defined.
- No asana task.
- CMS builds are breaking on the latest version of EDS, `document` is being referenced while Gatsby is building. 
- Errors out on: `error "document" is not available during server side rendering`
- [Gatsby documentation on this issue](https://www.gatsbyjs.org/docs/debugging-html-builds/)
**Is this a new component? Please review these reminders:**
Existing component.
- https://github.com/getethos/cms/pull/2930
**Full error log**
```
11:27:30 AM: failed Building static HTML for pages - 28.680s
11:27:30 AM: error "document" is not available during server side rendering.
11:27:30 AM:   17 |   const …
```
> Check for document before referencing in Portal

- package.json
- src/components/Portal/Portal.js
- Might have jumped the gun on #319, as I'm still seeing errors on CMS.
- Needed to move `return` up one level and add `null`.
- Checked this branch on a CMS deploy before assuming it resolves the issue (should have done that the first go round...).
- Resolved build off this branch: https://app.netlify.com/sites/ethos-cms/deploys/5e94d59824db1900072ace3a
- Failed build off of v1.1.166 from #319: https://app.netlify.com/sites/ethos-cms/deploys/5e94cf4c417e930006053bd9
- Demo of `Modal` which uses `Portal`: https://5e94d59824db1900072ace3a--ethos-cms.netlify.com/demo/EstimateWidget/ (fill out, click continue, click Save Estimates to see Modal)
> Portal document reference follow up

- package.json
- src/components/AsyncTypeahead/AsyncTypeahead.js
- src/hooks/usePopoverNavigation.js
- src/nora/components/KabobMenu/KabobMenuContainer.js
- [Asana Task](https://app.asana.com/0/1150068311310825/1170387956248380/f)
- Fix issue with kabob and data grid competing for focus
- Fix issue where when you navigate down from Grid after already having focus on the Kabob's trigger button, it would open that popover (even though we're now on the next trigger button down by 1 row)
___
**Manual Testing:**
I have a dirty Nora branch where I've been verifying all these changes in the data grid. This fixed the two bugs 🙌
> Data grid's keydown listener competing with popover listener bugz

- src/components/TextAreaInput/TextAreaInput.js
- src/components/TextInput/TextInput.js
- src/nora/components/NoraTextAreaInput/NoraTextAreaInput.js
- Noticed that the console in Nora was printing out some logs so figured I'd remove them from the Text related fields.
-
> Remove console.log from text inputs

- package.json
- src/components/UniversalNavbarExpanded/MobileNav/SecondaryLinks.js
- src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.d.ts
- src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.js
- src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.md
- src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.module.scss
- src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.test.js
- src/components/UniversalNavbarExpanded/__snapshots__/UniversalNavbarExpanded.test.js.snap
- Would like to merge by EOD April 23rd if possible.
- Diff is largely made up of snapshot update! Changes are smaller than they look.
- [Asana Task](https://app.asana.com/0/1116481661798430/1166819983224779/f)
- Need some Optimizely Web selectors and additional copy in the navbar, for running some CMS side experiment targeting on all pages.
**Is this a new component? Please review these reminders:**
Not a new component.
- https://github.com/getethos/cms/pull/2930 (original estimate widget PR - being broken into multiple smaller PRs)
> CMS Estimate experiment in UniversalNavbarExpanded

- src/components/Select/Select.js
- src/components/Select/Select.md
- src/components/Select/Select.test.js
- src/components/Select/__snapshots__/Select.test.js.snap
- src/components/index.d.ts
- src/components/index.tests.tsx
- Based on a PR comment (https://github.com/getethos/ethos/pull/3194#pullrequestreview-405364329), adds an `aria-label` to the `Select` component for a11y
- Adds a `data-tid` prop to `Select`
- Adds snapshot tests
Reference but does not depend on these changes
- https://github.com/getethos/ethos/pull/3194
> Add aria-label and data-tid props

- package.json
- src/components/Caption2.md
- src/components/Stepper/Stepper.js
- src/components/Stepper/Stepper.module.scss
- src/components/Type2/TitleLarge2.md
- src/components/Type2/TitleMedium2.md
- src/components/Type2/TitleSmall2.md
- src/components/Type2/TitleXLarge2.md
- src/components/TypeBase/TypeBase.js
- [Asana Task](https://app.asana.com/0/1147552137426708/1171609519486689/f)
- Updates the Stepper to use the Type 2 system
- Adds some documentation to EDS on Type 2 system examples making it super clear that you can use any of the type base "public props"
- https://github.com/getethos/ethos/pull/3237
Did same as above for all the type 2 Title* component examples too
> Stepper p2 and type2 document public props usage

- package.json
- src/components/Grid/Pagination.js
- src/components/Grid/Pagination.md
- src/components/Grid/Pagination.test.js
- src/components/Grid/PaginationHelper.js
- src/components/Grid/PaginationHelper.test.js
- src/components/Grid/__snapshots__/Pagination.test.js.snap
- src/components/Grid/usePagination.js
- src/components/index.d.ts
- src/components/index.tests.tsx
- [Asana Task](https://app.asana.com/0/1150068311310825/1175073217963713/f)
- Adds start and end ellipsis based on current page, total pages and display limit
No
-
> Pagination with ellipsis - limit number of pages displayed at one time

- package.json
- src/components/Select/Select.js
- src/components/Select/Select.md
- src/components/Select/Select.test.js
- src/components/Select/__snapshots__/Select.test.js.snap
- src/components/Select/states-fixture.js
- src/components/index.d.ts
- src/components/index.tests.tsx
- [Asana Task](https://app.asana.com/0/1136962714401929/1155914817079659/f)
- EDS Select Initial Values and Validation
- Monorepo PR: https://github.com/getethos/ethos/pull/3312
- frontend/src/main/InsuranceApp/term/Apply/Greenhouse/AuraDe/AuraDeQuestionUi.js for AuraDeSearchQuestion case (Eric and Jas):
```
<AuraDeSearchField
{...fieldProps}
cacheOptions
isAsync
isMulti
loadOptions={loadOptions}
/>
```
For above, it looks like the "**What is your occupation?**" aura question uses this and is an interesting usage in terms of it's async. The Doctor question also appears to use Select indirectly but via _AuraDeSearchComponent_
- underwriting/nora/frontend/src/features/dashboard/Toolbar.tsx for the dashboard filters in toolbar (Steph)
- …
> Refactor selects

- package.json
- src/components/ButtonSelectGroup/ButtonSelectGroup.js
- src/components/ButtonSelectGroup/ButtonSelectGroup.test.js
- src/components/ButtonSelectGroup/OptionButton.js
- src/components/Faq/Faq.js
- src/components/Grid/Grid.md
- src/components/Grid/Pagination.md
- src/components/Grid/usePagination.js
- src/components/Images/Images.js
- src/components/Popover/Options.js
- src/components/RadioButtons/RadioButtons.js
- src/components/Stepper/Stepper.js
- src/components/UniversalNavbar/constants.js
- src/components/ValueProps/ValueProps.js
- yarn.lock
The `uuid` package recently published a breaking change that changed the packages exports from a deep `export` to named `exports`. This PR explicitly pulls in `uuid` as a dependency, which prior to this change was being pulled in transitively, and updates the import statements to match the new `export` strategy.
-
> [Chore] updating uuid/v4 imports statements

- package.json
- src/nora/components/NoraButton/NoraButton.module.scss
- [Asana Task](https://app.asana.com/0/1150068311310825/1178718765502761/f)
All blue buttons in Nora have black outline:
But none of the blue buttons have black border in Figma:
-
> Remove border from NoraButton

- package.json
- src/components/DateInput/DateInput.js
- [Asana Task](https://app.asana.com/0/1135109139115239/1179984035109347)
- Date input wasn't passing `disabled` prop through, so you couldn't disabled it.
-
https://github.com/getethos/ethos/pull/3891
-
**Before**
**After**
> Add `disabled` prop to DateInput

- src/components/ButtonSelectGroup/OptionButton.js
- Adds data-tid for button select group options. Helpful for E2E testing
-
-
> Add data-tid for button select group options

- package.json
- src/components/Button/Button.module.scss
- src/components/fa.js
- [Asana Task](https://app.asana.com/0/1116481661798430/1198986488532933)
- change padding for all screen sizes to 16px for full width arrow icon button
-
> change padding for all screen sizes to 16px for full width arrow icon button

- package.json
- src/components/BirthdateInput/BirthdateInput.js
- src/components/BirthdateInput/BirthdateInput.test.js
- src/components/BirthdateInput/__snapshots__/BirthdateInput.test.js.snap
- src/components/DateInput/DateInput.js
- src/components/DateInput/DateInput.test.js
- src/components/DateInput/__snapshots__/DateInput.test.js.snap
- src/components/EmailInput/EmailInput.js
- src/components/EmailInput/EmailInput.test.js
- src/components/EmailInput/__snapshots__/EmailInput.test.js.snap
- src/components/NumberInput/NumberInput.js
- src/components/NumberInput/NumberInput.test.js
- src/components/NumberInput/__snapshots__/NumberInput.test.js.snap
- src/components/TextInput/TextInput.js
- src/components/TextInput/TextInput.test.js
- src/components/TextInput/__snapshots__/TextInput.test.js.snap
- src/components/TextMaskedInput/TextMaskedInput.js
- src/components/ZipInput/ZipInput.js
- src/components/ZipInput/ZipInput.test.js
- src/components/ZipInput/__snapshots__/ZipInput.test.js.snap
- [Asana Task](https://app.asana.com/0/1116481661798430/1199675528419605)
- Add autoComplete attribute to various fields
-
> Add autoComplete attribute to input fields

- package.json
- src/components/TextMaskedInput/TextMaskedInput.js
-
- Fixing a bug found in this PR: https://github.com/getethos/ethos/pull/6885
- The `onBlur` validator was jacking the `onClick` event making it so you had to click a button twice after the validation in order to register a click.
- This solution fires the `onBlur` event after a timeout, which allows the `onClick` to register and then the `onBlur` to occur afterwards.
**Notes**
----
----
**Previous version**
**Updated version**
**Updated - validation still occurs**
**Updated - validation still occurs**
> Add timeout to onBlur for MaskedInput

- package.json
- src/components/TextAreaInput/BaseTextAreaInput.js
- src/components/TextAreaInput/TextAreaInput.js
- Adds the `rows` property which is native HTML to the textarea component to allow changing the height of the component
- https://github.com/getethos/ethos/pull/6953
> Add rows to textarea

- package.json
- src/components/Faq/Faq.module.scss
Removing the extra default chevron within the `<summary>` tag
- [Asana Task] 
- https://app.asana.com/0/1200303476344966/1200235184322292/f
No
Before:
After:
> remove extra chevron from summary tag

- package.json
- src/components/UniversalNavbar/UniversalNavbar.module.scss
- src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.module.scss
- Reduces width of navbar on desktop viewports to match container width of modules on CMS.
- [Deploy preview](https://deploy-preview-4418--ethos-cms.netlify.app/)
- [Asana Task](https://app.asana.com/0/1200303476344966/1200517990013519/f)
- [Related CMS PR](https://github.com/getethos/cms/pull/4418)
- [Figma](https://www.figma.com/file/ZPTR8VwjUphHpOTD9njzxS/Homepage-markup?node-id=0%3A1)
Reduces UniversalNavbarExpanded and UniversalNavbar components width. 
> Adjust universal navbar width

- package.json
- src/components/UniversalNavbarExpanded/CtaButton.js
- src/components/UniversalNavbarExpanded/MobileNav/MobileNav.js
- src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.js
- src/components/UniversalNavbarExpanded/__snapshots__/UniversalNavbarExpanded.test.js.snap
- As part of the changes for agent landing pages in the CMS, we required an alternate CTA button title for the `UniversalNavbarExpanded`. 
- This PR removes the hardcoded "Check my price" value from the `CtaButton` and replaces it with the value of the `links.CTA.title` that is passed into the `UniversalNavbarExpanded` component.
- https://github.com/getethos/cms/pull/4476
Using this new branch in the CMS to test. "Get started"
Styleguide running locally. "Check my price"
> CtaButton copy parameter in UniversalNavbarExpanded

- package.json
- src/components/UniversalNavbarExpanded/DropdownNav/DropdownChildren.js
- src/components/UniversalNavbarExpanded/DropdownNav/DropdownChildren.module.scss
- src/components/UniversalNavbarExpanded/DropdownNav/DropdownCta.js
- src/components/UniversalNavbarExpanded/DropdownNav/DropdownNav.js
- src/components/UniversalNavbarExpanded/DropdownNav/IconIntegratedTitle.js
- src/components/UniversalNavbarExpanded/SampleContent.js
- src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.js
- src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.md
- src/components/UniversalNavbarExpanded/__snapshots__/UniversalNavbarExpanded.test.js.snap
- Adds an option to pass an alternate icon through to CTA subnav items.
- Adds options to hide the account and search icons.
- [Jira Task for alternate icon](https://ethoslife.atlassian.net/browse/ALP-16?atlOrigin=eyJpIjoiM2ZjNTNkMDE3ZmM3NGM5NmEzY2MyMGM4MmQzMGIzOWIiLCJwIjoiaiJ9)
- [Jira Task for hiding icons](https://ethoslife.atlassian.net/browse/ALP-13?atlOrigin=eyJpIjoiNTgxODZjMTEyODM2NGM3NmFjOGQwNjBjZDI3Mjc0ZmUiLCJwIjoiaiJ9)
Alternate play icon with hidden search & account icons.
*
> UniversalNavbarExpanded - hide icons and alternate cta icon options

- package.json
- src/components/UniversalNavbarExpanded/SampleContent.js
- src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.js
- src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.md
- src/components/UniversalNavbarExpanded/__snapshots__/UniversalNavbarExpanded.test.js.snap
- [Jira Task](https://ethoslife.atlassian.net/browse/ALPP-9?atlOrigin=eyJpIjoiZmVlMjY3YjIyZGZmNDVmOTk3ZDc2NmRhMjkwYjUxYzUiLCJwIjoiaiJ9)
- Adds a new secondary cta text link to the UniversalNavbarExpanded component
New "login" link
> Add secondary cta to navbar

- package.json
I accidentally used the tag [v1.2.14](https://github.com/getethos/ethos-design-system/releases/tag/v1.2.14) for #418 which only bumped the package.json version to v1.2.13. So when Harry bumped to v1.2.14 in package.json for #421, the tag was already taken. 
This PR resolves the issue by bumping the version to v1.2.15 and introducing the [v1.2.15](https://github.com/getethos/ethos-design-system/releases/tag/v1.2.15) tag after Harry's work has been merged.
> Tag version fix: v1.2.15

- package.json
- src/components/NumberInput/NumberInput.js
- src/components/TextMaskedInput/TextMaskedInput.js
- src/components/index.d.ts
https://user-images.githubusercontent.com/84357906/146617248-4ca54122-a601-4bdf-ba14-80d0966b7f6f.mov
Home Page:
- now we can use `maxLength` to control the max number of characters allowed in `NumberInput` component
> Enable maxLength for NumberInput

- package.json
- src/components/Tooltip/Tooltip.js
- src/components/Tooltip/Tooltip.md
- src/components/Tooltip/Tooltip.module.scss
- src/components/Tooltip/Tooltip.test.js
- src/components/Tooltip/TooltipExamples.module.scss
- src/components/Tooltip/__snapshots__/Tooltip.test.js.snap
- src/components/index.d.ts
<TO BE ADDED SOON>
Mobile Tooltip (with soft edges):
===
Desktop Tooltip (with soft edges):
===
Mobile tooltip (Backward compatibility with rough edges):
===
Desktop tooltip (Backward compatibility with rough edges):
===
Default Tooltip with soft corner = false:
===
Demo Page:
===
>  [Tooltip Change]: Enhance tooltip to allow multi lines & soft edges

- package.json
- src/components/Select/Select.js
- Saw this originally when running through LGA Prime on physician question, then also realized [CC-377](https://ethoslife.atlassian.net/browse/CC-377) was due to the same error so I wanted to fix it
> [BUG] Fix Select Component Error Validation

- package.json
- src/components/Select/Select.js
- reverts what happened in https://github.com/getethos/ethos-design-system/pull/436
- Basically the validators for select didn't like that we used empty string for value [code](https://github.com/getethos/ethos/blob/d9e593a68944a7e94c9159dc1e295fee947825ec/frontend/src/main/InsuranceApp/PreInterview/Questions/validators.ts#L110)
- This fixes that while still fixing the underlying issue of the console error being thrown on initial select Blur
> Bug fix for select component

- package.json
- src/components/ValueProps/ValueProps.js
-
- allows for element as prop type so that text passed to value props can be bolded and changed
> Explicitly define proptypes for valueprops, allow for element

- package.json
- src/components/index.d.ts
-
- update typescript definitions for previous release
> [ValueProps] - improve Typescript definitions to remove errors

- package.json
- src/components/BirthdateInput/__snapshots__/BirthdateInput.test.js.snap
- src/components/DateInput/__snapshots__/DateInput.test.js.snap
- src/components/EmailInput/EmailInput.js
- src/components/EmailInput/EmailInput.md
- src/components/EmailInput/__snapshots__/EmailInput.test.js.snap
- src/components/NumberInput/NumberInput.js
- src/components/NumberInput/NumberInput.md
- src/components/NumberInput/__snapshots__/NumberInput.test.js.snap
- src/components/PasswordInput/__snapshots__/PasswordInput.test.js.snap
- src/components/TextInput/TextInput.js
- src/components/TextInput/TextInput.md
- src/components/TextInput/TextInput.module.scss
- src/components/TextInput/__snapshots__/TextInput.test.js.snap
- src/components/TextMaskedInput/TextMaskedInput.js
- src/components/TextMaskedInput/TextMaskedInput.md
- src/components/ZipInput/__snapshots__/ZipInput.test.js.snap
- src/components/fa.js
- src/components/index.d.ts
- src/helpers/constants.js
-
- added options: iconName and iconPrefix to TextInput, EmailInput, NumberInput to allow icon display inside input
- related examples are added at markdown file for TextInput, EmailInput, NumberInput
> Add an icon option for TextInput EmailInput NumberInput

- src/components/index.d.ts
Simple update to mark `<CloudinaryImage >` typescript definition props as optional to follow the components required props.
https://github.com/getethos/ethos-design-system/blob/master/src/components/Images/Images.js#L38
> follow required props of CloudinaryImage component, make props optional

- package.json
- src/components/NumberInput/NumberInput.js
- src/components/Tooltip/Tooltip.module.scss
- src/components/index.d.ts
https://user-images.githubusercontent.com/84357906/176282490-dbb4226c-3827-45a5-8830-d5d98410c48a.mov
> Fix Modal X button in Safari and Add style overrides for `NumberInput` Component

- package.json
- src/components/Tooltip/Tooltip.js
- src/components/Tooltip/Tooltip.md
Follow up to #468 . Prevent excessive tracking events from firing on subsequent hovers or mobile modal interaction.
> Only fire trackingFunction in ToolTip once

- package.json
- src/components/Media/Media.js
- yarn.lock
-
- Remove `Media` component and `react-responsive` dependency. This was already deprecated.
- Going to wait to create a version for this until after preload work is done.
> [GC-1561] Deprecate Media, remove react-responsive

- package.json
- src/components/Variables.scss
In main app the following z-index value are used for BaseModal:
```
$base-modal-backdrop-z-index: 20;
$base-modal-modal-z-index: 21;
```
This PR makes the EDS Modal have a lower z-index to account for when BaseModal is nested inside of EDS Modal, like with the ACH details on the payment modal in checkout.
-
> Lower z-index for Modal to be compatible with nested BaseModal in main app

- package.json
- src/components/Button/Button.js
- src/components/Button/Button.md
- src/components/Button/Button.module.scss
- src/components/Colors.js
- src/components/Colors.scss
- src/components/design-system.css
- src/components/index.d.ts
- stats.json
- styleguide/content/color/color.md
- styleguide/content/color/color.scss
Supports new buttons used in multiple modules for the new homepage rebrand design experiment.
Easier to add the new color here than to write custom CSS to replicate button styles in CMS. 
The color variable will also be required for some custom CSS in CMS for this experiment as well.
https://github.com/getethos/cms/pull/6876
> [GC-1625] New Cypress color & button style used in homepage color palette experiment

- package.json
- src/components/Images/Images.js
- src/components/Images/Images.module.scss
- src/components/Images/__snapshots__/Images.spec.js.snap
- yarn.lock
**lazy load in live**
https://user-images.githubusercontent.com/84357906/211723439-a2a7b665-68be-47ae-972c-7ec8d13532d4.mov
**current**
- During the initial page load we are sending `67` requests for `564kb` resource to be transferred 
**post-change**
-  During the initial page load we are sending `14` total requests for `201kb` resource to be transferred
> Lazy Load Cloudinary Resource

- package.json
- src/components/Button/Button.js
- src/components/Button/Button.md
- src/components/Button/Button.module.scss
- src/components/Colors.js
- src/components/Colors.scss
- src/components/design-system.css
- src/components/index.d.ts
- stats.json
- styleguide/content/color/color.md
- styleguide/content/color/color.scss
New color and button to support updated SingleCTA module layout in CMS for HP color palette experiment.
- WIP
> Introduce lime color + lime button for HP color palette rebrand experiment

- package.json
- src/components/Tooltip/Tooltip.js
[GC-1076](https://ethoslife.atlassian.net/browse/GC-1076?atlOrigin=eyJpIjoiZGZmMzczNmRhZmNlNDkxM2I2ZmNjZjRiNWZhNjBlYjMiLCJwIjoiaiJ9)
- https://ethoslife.atlassian.net/browse/GC-1076?atlOrigin=eyJpIjoiZGZmMzczNmRhZmNlNDkxM2I2ZmNjZjRiNWZhNjBlYjMiLCJwIjoiaiJ9
- https://ethoslife.atlassian.net/browse/GC-1078?atlOrigin=eyJpIjoiZWRjOGY1ZWRiNmI0NDg4ODg4ZWU3MjYxMmFmZTlmYjciLCJwIjoiaiJ9
[GC-1078]: https://ethoslife.atlassian.net/browse/GC-1078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GC-1076]: https://ethoslife.atlassian.net/browse/GC-1076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Make tooltip device independent interactable

- package.json
- src/components/Button/Button.js
- src/components/Button/Button.md
- src/components/Button/Button.module.scss
- src/components/Colors.js
- src/components/Colors.scss
- src/components/design-system.css
- src/components/index.d.ts
- stats.json
- styleguide/content/color/color.md
- styleguide/content/color/color.scss
Support for CMS new SingleCTA module variation where Dark Salamander color button is used.
- WIP
> dark salamander button

- package.json
- src/components/Layout/Layout.js
This PR fix the issue when navigating back, the navigation bar should turn to white color if the user is not at the top of the page
https://github.com/getethos/cms/pull/7030
Screenshots and manual test instruction is in this PR https://github.com/getethos/cms/pull/7030
> [GC-1964] [NSLP follow up] On navigate back, useEffect to set initial background to white if scrolled

- src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.js
- src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.md
- src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.module.scss
- src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.test.js
- src/components/UniversalNavbarExpanded/__snapshots__/UniversalNavbarExpanded.test.js.snap
In the CMS homepage rebrand experiment we want to update the NS_MOSS treatment to only have an animated/transparent background on desktop but not mobile. This PR enables that capability in the UniversalNavbarExpanded component. 
- TBD
https://user-images.githubusercontent.com/87672141/226066574-6810144f-863f-4053-86d0-00d0dcf8e801.mov
> [GC-2063] UniversalNavbarExpanded: Differentiate between mobile & desktop animated background

- package.json
- src/components/CheckboxInput2/CheckboxInput2.js
- src/components/CheckboxInput2/__snapshots__/CheckboxInput2.test.js.snap
added new optional property to the checkboxinput2 component, to pass in data to formotiv for behavioral analysis.
-
Tested the new eds component in local by using it with and without (change in local code) the new property in the checkbox type ask in main interview.
screenshot with the new data-formotiv property.
screenshot without the new data-formotiv property (note that data-formotiv is blank as default value)
> [RP-496] add optional data field for formotiv in checkboxinput 2

- package.json
- src/components/UniversalNavbarExpanded/DropdownNav/NestedCategories/CategoryLinks.js
- src/components/UniversalNavbarExpanded/DropdownNav/NestedCategories/NestedCategories.js
- src/components/UniversalNavbarExpanded/MobileNav/NestedLinks/NestedLinks.js
- src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.js
- https://github.com/getethos/cms-next/pull/219
Basically updated keys when mapping React components, so they do not throw errors.
> [GC-2691] universal navbar errors fix

- src/components/ZipInput/ZipInput.js
> add disabled prop to ZipInput

- .github/workflows/deploy.yml
> remove deprecated yarn flag

- src/components/UniversalNavbar/UniversalNavbar.d.ts
- src/components/UniversalNavbarExpanded/MobileNav/MobileNav.js
- src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.js
- [CEQ2-164] feat: universal navbar support for renderCtaButton
- https://github.com/getethos/cms-next/pull/1889
See the [PR](https://github.com/getethos/cms-next/pull/1889)
[CEQ2-164]: https://ethoslife.atlassian.net/browse/CEQ2-164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CEQ2-164] feat: universal navbar support for renderCtaButton

- package.json
- src/components/Button/Button.js
- Add data-track-button and data-properties attributes to Button
- Default value of data-track-button will be true
-
> [ceq2-1596] feat: add data attributes to Button 
