getethos/ethos-design-system

src/components/Inputs/BirthdateInput/BirthdateInput.js

https://app.asana.com/0/1136962714401929/1138726622315604/f
We'll want to abstract this soon so it's better shared across the inputs but...

Add in the error handling for birthdate too

---

src/components/Images/Images.js

See: https://github.com/getethos/cms/pull/1728

Changes Cloudinary Images DPR from hardcode of 2 to auto responsive detection

---

src/helpers/restrict.js
src/helpers/restrict.test.js

Hotfix for bug discovered in Megan's PR

Fix bug with restrict not allowing ampersand so thus blocking valid email

---

src/components/Form/Form.md
src/components/Form/example-mappers.js
src/components/Inputs/BirthdateInput/BirthdateInput.js
src/components/Inputs/BirthdateInput/BirthdateInput.md
src/components/Inputs/BirthdateInput/BirthdateInput.test.js
src/components/Inputs/ButtonSelectGroup/ButtonSelectGroup.test.js
src/components/Inputs/ButtonSelectGroup/__snapshots__/ButtonSelectGroup.test.js.snap
src/validators/BirthdateInputValidator.js

Check form.md for an example
**Working form**
**Working form with error handling**
**Working original birthdate input**

Birthdate field works in `<Form>`

---

src/components/Form/Form.md
src/components/Inputs/ZipInput/ZipInput.js
src/components/Inputs/ZipInput/ZipInput.md
src/components/Inputs/ZipInput/ZipInputValidator.js

- [Use numeric keypad in Zip and Birthdate inputs](https://app.asana.com/0/1137984670709817/1141266157761029/f)
- [Use numeric mask in ZipCodeInput](https://app.asana.com/0/1137984670709817/1141266157761037/f)
- 

Qw ii rz cleanup zipinput

---

src/components/Form/Form.js
src/components/Form/Form.md
src/components/Inputs/ButtonSelectGroup/ButtonSelectGroup.md
src/hooks/useFormState.js
src/validators/validateTruthy.js

___
- [Asana Task](https://app.asana.com/0/1137984670709817/1142882503761970/f)
- Form interacted with is now exposed to consumer
- 

Qw ii rz cleanup form interacted with

---

package.json
src/components/Inputs/BirthdateInput/BirthdateInput.js
src/components/Inputs/ZipInput/ZipInput.js

- [Asana Task](https://app.asana.com/0/1137984670709817/1141266157761037/f)
- Use numeric mask in ZipCodeInput
- 

Better number ux birthday zip

---

build/bundle.js
package.json
src/helpers/restrict.js
src/helpers/restrict.test.js

- [Asana Task](https://app.asana.com/0/1137984670709817/1143293029720137/f)
- Restrict is too prohibitive
This came from call center folks admin via @mwwu

More permissive blacklist

---

src/components/UniversalNavbar/UniversalNavbar.js

- `/login` is not an internal link in the CMS
- uuid for keys and non link component for /login

No LinkComponent for /login

---

src/components/UniversalNavbar/UniversalNavbar.js
src/components/UniversalNavbar/UniversalNavbar.scss
src/components/UniversalNavbar/__snapshots__/UniversalNavbar.test.js.snap
src/components/design-system.css

Remove react media in Universal Nav Bar and Updated proptypes

---

package.json

Move peer dependencies to regular dependencies

---

src/components/UniversalNavbar/UniversalNavbar.js

Fix universal nav bar Proptypes

---

src/components/Form/Form.md

Bug found on @roblevintennis  's comment here: 
https://github.com/getethos/cms/pull/1940#pullrequestreview-300355675
Updating the `Form.md` markdown file with the new `validateMinMaxDateFactory` arguments
Previous:
Updated:

Update Form.md markdown file with Birthdate Input validator

---

package.json
src/components/Inputs/BirthdateInput/__snapshots__/BirthdateInput.test.js.snap
src/components/Inputs/TextMaskedInput/TextMaskedInput.js

- [Asana Task](https://app.asana.com/0/1136962714401929/1144809619356369/f)
- Fix the all caps issue causing QW to regress

allCaps: true is the correct default

---

src/components/Inputs/PasswordInput/PasswordInput.js
src/components/Inputs/PasswordInput/PasswordInput.md
src/components/Inputs/PasswordInput/PasswordInput.test.js
src/components/Inputs/PasswordInput/__snapshots__/PasswordInput.test.js.snap
src/components/Inputs/PasswordInput/index.js
src/components/Inputs/TextInput/TextInput.js
src/validators/validatePassword.js
src/validators/validatePassword.test.js

- [Asana Task](https://app.asana.com/0/1136962714401929/1144809619356373/f)
- Password field for Unum create page
Invalid characters missing:
Invalid empty:
Valid:

Unum password etc

---

src/components/Inputs/BirthdateInput/BirthdateInput.js

Numberinput pr created a bug in birthdateinput.
To reproduce run styleguide and try typing a birthdate, it will throw. This fixes it

Bugfix for birthdate

---

package.json

Bump pre-release version

---

src/components/Inputs/ButtonSelectGroup/ButtonSelectGroup.js
src/components/Inputs/ButtonSelectGroup/ButtonSelectGroup.md

Fix button select group initial falsy value not working (More type coercion bugs!!)

---

src/components/Inputs/ButtonSelectGroup/ButtonGroup.module.scss
src/components/Inputs/ButtonSelectGroup/ButtonSelectGroup.js
src/components/Inputs/ButtonSelectGroup/ButtonSelectGroup.md

Needed for new nicotine form: https://www.figma.com/file/iqso07OsIaQtm90DcctT5A/Unum?node-id=826%3A125

Add 'column' property which stacks buttons

---

src/components/Form/Form.md
src/components/Inputs/ButtonSelectGroup/ButtonSelectGroup.js
src/components/Inputs/ButtonSelectGroup/ButtonSelectGroup.md
src/components/Inputs/CheckboxInput/CheckboxInput.md
src/components/Inputs/TextInput/TextInput.md
src/validators/validateTruthy.js
src/validators/validateTruthy.test.js

For the new example in BSG you have to __click the False button__:

Remove validateTruthy

---

src/components/Inputs/TextInput/TextInput.js

`event` is incorrect in the `onChange` function in the `TextInput` component

[Bug fix] Fix event in onChange in TextInput

---

README.md
package.json
src/components/Form/BugInForm.js.example
src/components/Form/BugInForm.md.example
src/components/Form/Form.js
src/components/Form/Form.md
src/hooks/useFormState.js
src/hooks/useFormState.test.js

- [Asana Task](https://app.asana.com/0/1136962714401929/1145702600849513/f)
- This PR fixes a bug @kenning found which he provided on an early commit to the Form.md file. Essentially, it's a bug for dynamic fields.
-  Dynamic fields & hidden fields—if you call  when a dynamic field is hidden, it
will not be considered in determining form validity. Further, if the hidden field has
been previously interacted with, it's value will also be ignored.
- It also adds some documentation in the README for the engine node requirements and how to update so `nvm` `avn` et al are happy

Dynamic fields problem

---

src/components/Inputs/BirthdateInput/BirthdateInput.js
src/components/Inputs/CheckboxInput/CheckboxInput.js
src/components/Inputs/TextAreaInput/TextAreaInput.js
src/components/Inputs/TextInput/TextInput.js
src/components/Inputs/TextMaskedInput/TextMaskedInput.js

- [Asana Task](https://app.asana.com/0/1136962714401929/1146729483498353/f)
- Follow up EDS Tasks:
- Make setFieldTouched calls fault tolerant

Make setFieldTouched calls fault tolerant

---

.eslintignore
src/components/Inputs/BirthdateInput/BirthdateInput.js
src/components/Inputs/ButtonSelectGroup/ButtonSelectGroup.test.js
src/components/Inputs/TextAreaInput/TextAreaInput.js
src/components/Inputs/TextInput/TextInput.js
src/components/Inputs/TextMaskedInput/TextMaskedInput.js
src/components/Inputs/ZipInput/ZipInput.js
src/components/UniversalNavbar/UniversalNavbar.js
src/hooks/useInputValidation.js

- [Asana Task](https://app.asana.com/0/1136962714401929/1146342193058673)
- Earlier we had ~140 lint errors. This fixes a handful. I'm trying to break this into small PRs.
- @roblevintennis take a glance at the ternaries at the end? I think they're fine but on an earlier run I thought I saw them get mangled. (See also: https://prettier.io/docs/en/cli.html#debug-check)

Fix lint problems (round 1)

---

src/components/Button/Button.js
src/components/Button/Button.md
src/components/Button/Button.module.scss

also necessary for https://app.asana.com/0/1116481661798430/1136005494202191

Make a back arrow button

---

src/components/Inputs/BirthdateInput/BirthdateInput.js
src/components/Inputs/ButtonSelectGroup/ButtonSelectGroup.js
src/components/Inputs/ButtonSelectGroup/ButtonSelectGroup.test.js
src/components/Inputs/CheckboxInput/CheckboxInput.js
src/components/Inputs/EmailInput/EmailInput.js
src/components/Inputs/NumberInput/NumberInput.js
src/components/Inputs/TextAreaInput/TextAreaInput.js
src/components/Inputs/TextInput/TextInput.js
src/components/Inputs/TextMaskedInput/TextMaskedInput.js
src/components/Inputs/ZipInput/ZipInput.js
src/components/Spacer/Spacer.test.js

- Previously: #130
- If we merge these branches in order, we'd be down to 63.

Fix lint errors (e.g. remove unused hook vars)

---

src/components/UniversalNavbar/UniversalNavbar.js

necessary for https://app.asana.com/0/1116481661798430/1136005494202191

Add ability to hide cta on desktop to navbar

---

src/components/Inputs/CheckboxInput/CheckboxInput.js
src/components/Inputs/CheckboxInput/CheckboxInput.md
src/components/Inputs/CheckboxInput/CheckboxInput.module.scss
src/components/Inputs/CheckboxInput/__snapshots__/CheckboxInput.test.js.snap
src/hooks/useErrorMessage.js
src/hooks/useFormState.js
src/hooks/useFormState.test.js
src/hooks/useInvalid.js
src/hooks/useRequired.js

- [Asana Task](https://app.asana.com/0/1136962714401929/1147477344968945/f)
- Fix Checkbox not turning red border when error
-  `src/hooks/useErrorMessage.js` more fault tolerant on internal props passed in via a white list
- some linting too

Lint issues ii + Checkbox bugfix

---

package.json
src/components/Inputs/ButtonSelectGroup/ButtonSelectGroup.js
src/components/Inputs/ButtonSelectGroup/OptionButton.js

This plus the pending branches take us down to ~30 issues.

Add ButtonSelectGroup propTypes

---

src/components/Form/DangerouslyUseFormGroups.js
src/components/InfoMessage/InfoMessage.js
src/components/Inputs/ButtonSelectGroup/ButtonSelectGroup.js
src/components/Inputs/CheckboxInput/CheckboxInput.js
src/components/Inputs/EmailInput/EmailInput.js
src/components/Layout/Layout.js

- [Asana Task](https://app.asana.com/0/1136962714401929/1146342193058673/f)
- Fixes rest of prop type warning besides Form.js (once https://github.com/getethos/ethos-design-system/pull/139 is also in)

Fix more issues found with PropTypes

---

.eslintrc.js
package.json
src/components/Inputs/CheckboxInput/CheckboxInput.js
src/components/Layout/Layout.js

Fix last lint errors

---

src/components/UniversalNavbar/UniversalNavbar.js
src/components/UniversalNavbar/__snapshots__/UniversalNavbar.test.js.snap

Request from growth team
https://app.asana.com/0/1116481661798430/1146907278858981

Change 'blog' link to 'faq'

---

src/components/Inputs/RadioButtons/RadioButtons.js

This is just a couple of follow up items from Alex's feedback for already merged:
https://github.com/getethos/ethos-design-system/pull/145

Fix some things from Alex's feedback on PR

---

package.json
src/components/Form/Form.md
src/components/Inputs/BirthdateInput/BirthdateInput.md

- [Asana Task](https://app.asana.com/0/1136962714401929/1148773948505985/f)
- Prefilled BirthdateInput with `initialValue` should enabled the form's Continue button

Adds a prefilled BirthdateInput field example that is wrapped in a form.

---

package.json
src/components/Button/Button.module.scss

- [Asana Task](https://app.asana.com/0/1136962714401929/1149059915979449)
- This may fix the leakage of Button styles that Matt reported. Verifying.

Remove button tag from Button.module.scss

---

bin/deploy.sh
package.json

Related PRs:
- CloudFront https redirect https://github.com/getethos/stack/pull/202
- Deploy EDS via S3 website https://github.com/getethos/ethos-design-system/pull/151

Invalidate EDS CloudFront on deploy

---

.github/workflows/deploy.yml

Test PR events with GH actions

Test comment, open PR

---

package.json
src/components/Select/Select.js
src/components/Select/Select.md

- Will be used in this ticket: [Special Auth in flow](https://app.asana.com/0/1149628124018183/1150703512578001)
- Adds react-select/creatable component by providing isCreatable prop to our Select component.
- Also adds react-select/async-creatable for the case where both isAsync and isCreatable are passed as props.

Adds react-select/creatable and react-select/async-creatable to Select Component

---

package.json
yarn.lock

- [Context](https://github.com/getethos/ethos-design-system/network/alert/yarn.lock/serialize-javascript/open)

Upgrade react-styleguidist to latest (v10.2.1)

---

package.json
src/components/index.d.ts
src/components/index.tests.tsx
src/components/tsconfig.json
yarn.lock

[Rob] Background: I had asked Tamir if he could add typescript typings for Faq and it resuled in this PR. I've piggy-backed off his work to make verification within EDS easier.
Faq in EDS:

add faq to index.d.ts

---

src/components/index.d.ts
src/components/index.tests.tsx

- [Asana Task](https://app.asana.com/0/1137984670709817/1155343635039372/f)
- CheckboxInput typings
Verification

Stronger types for CheckboxInput

---

src/components/index.d.ts
src/components/index.tests.tsx

Stronger types for ButtonSelectGroup

---

src/components/index.d.ts
src/components/index.tests.tsx

Stronger types for Select

---

src/components/index.d.ts
src/components/index.tests.tsx

ValueProps typing improvements

---

src/components/index.d.ts
src/components/index.tests.tsx

RadioButtonGroup typing improvements

---

src/components/EmailInput/EmailInput.js
src/components/index.d.ts
src/components/index.tests.tsx

Typing improvements email input

---

src/components/index.d.ts

- OptionButton typings
_Note that we already have `ButtonSelectGroupTest` test which uses this `ButtonSelectGroup.Option` and that test still passes_

OptionButton typing improvements

---

src/components/index.d.ts
src/components/index.tests.tsx

TextMaskedInput typing improvements

---

src/components/index.d.ts
src/components/index.tests.tsx

ZipInput typing improvements

---

src/components/index.d.ts
src/components/index.tests.tsx

- TextMaskedInput typings -- follow up for Brad's feedback on https://github.com/getethos/ethos-design-system/pull/211

Betting typing for methods in TextMaskedInput

---

src/components/index.d.ts

- [Asana Task](https://app.asana.com/0/1137984670709817/1155343635039372/f)
- Button
- `children: React.ReactNode` (from `:any`)
- 

Button and children: React.ReactNode

---

src/components/index.d.ts

- [Asana Task](https://app.asana.com/0/1137984670709817/1155343635039372/f)
- Grid et al Typing

A bit of TLC to the Grid typings.

---

package.json
src/components/Select/Select.js

**Asana** [https://app.asana.com/0/1136962714401929/1155914817079659/f] -- EDS Select Initial Values and Validation
- If you specify an initial value on the select box, then onblur without changing the value, validateExists, for example, would fail since the selectedValue is initially set to undefined instead of the passed in value.

Fixes initial values and validation for Select

---

package.json
src/nora/components/Colors.css
src/nora/components/Example/Example.js
src/nora/components/Header/Header.js
src/nora/components/Header/Header.md
src/nora/components/Header/Header.module.scss
src/nora/components/Header/Header.test.js
src/nora/components/Header/__snapshots__/Header.test.js.snap

…d total wip
- [Asana Task](https://app.asana.com/0/1150068311310825/1157190385219581/f)
- Nora Header component
After refactoring to take left children and right children props instead of the less flexible Title and Profile. Also, it adds `<nav>` which feels more semantic after doing a bit of research:
JSDocs:

Nora Header component

---

package.json
src/components/index.d.ts
src/components/index.js
src/components/index.tests.tsx
src/nora/components/Header/Header.js
src/nora/components/Header/Header.test.js
src/nora/components/Header/index.js
src/nora/components/Tag/Tag.js
src/nora/components/Tag/index.js
src/nora/components/index.js

- [Asana Task](https://app.asana.com/0/1150068311310825/1157190385219581/f)
- This is a part of the Nora Header work. We will need Tag and Header typings so we can consume in our Nora Typescript.
- Ran `yarn test:types` to verify

Nora header tags typings

---

package.json
src/components/Grid/Pagination.module.scss
src/components/Grid/Pagination.test.js
src/components/Grid/__snapshots__/Pagination.test.js.snap
src/components/Grid/usePagination.js

- Update pagination styles to be more in line with Nora specs.
- Out of scope: Font Awesome icons for left and right arrows
| Before | After | Mocks |
| --- | --- | --- |
| ![image](https://user-images.githubusercontent.com/12839832/72955968-03d96d80-3dd9-11ea-9080-38f079a30a25.png) | ![image](https://user-images.githubusercontent.com/12839832/72955989-118ef300-3dd9-11ea-8c24-c32038a552d9.png) | ![image (4)](https://user-images.githubusercontent.com/12839832/72956808-1e611600-3ddc-11ea-948b-0730fe4f4a71.png) |
-

Pagination styles

---

.travis.yml

Change travis.yml to make an .npmrc file in the before_install step using a secret.

Make Travis use fontawesome

---

.github/workflows/deploy.yml

Change github actions to set up .npmrc with fontawesome token.

Add support for fontawesome for github actions

---

README.md
package.json

No Asana--adds a section on CI/CD but also meant to test out the font awesome deployment refactors Alex just did work :)

Deployment and cicd

---

package.json

- Realized I need the Flex component that Rob had added in the last PR. Bumping the version here so I can use it. 
- 

Bump to v1.1.73

---

src/components/Modal/Modal.module.scss
src/components/UniversalNavbar/UniversalNavbar.js
src/components/UniversalNavbar/UniversalNavbar.module.scss
src/components/UniversalNavbar/__snapshots__/UniversalNavbar.test.js.snap
src/components/Variables.scss

Navbar covers top part of modal
Current interaction with Navbar and Modal
Fixed
- Using EDS Modal on CMS
**Manual Testing**
- Navbar and Modal interaction
- Universal Navbar still looks fine

Nav Bar covers top part of modal

---

package.json

- Covers https://github.com/getethos/ethos-design-system/pull/254
- 
- 

v1.1.77 Bump version

---

package.json
src/components/UniversalNavbar/UniversalNavbar.js
src/components/UniversalNavbar/UniversalNavbar.module.scss
src/components/UniversalNavbar/__snapshots__/UniversalNavbar.test.js.snap

- Navbar Fix. Needed outer div for a display block navbar
- Update yarn version
- Error: 
- 

Navbar fix

---

package.json

- Covers PR: https://github.com/getethos/ethos-design-system/pull/257
- 
- 

Bump version V1.1.79

---

src/components/ValueProps/ValueProps.js

- [Asana Task](https://app.asana.com/0/1116481661798430/1158265377944521)

Removed Assurity Life from Value Props component

---

package.json
src/components/index.d.ts
src/nora/components/IconLink/IconLink.js
src/nora/components/IconLink/IconLink.md
src/nora/components/IconLink/IconLink.test.js
src/nora/components/IconLink/__snapshots__/IconLink.test.js.snap

- [Asana Task](https://app.asana.com/0/1150068311310825/1160860624827041)
- When clicking an `IconLink` component, clicking either the text or the icon should provide the same behavior. 
- Main repo PR: https://github.com/getethos/ethos/pull/2335
| Current EDS | On this branch |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/12839832/74775521-b7a01280-524a-11ea-9930-80ee793aecd7.png) | ![image](https://user-images.githubusercontent.com/12839832/74775605-e322fd00-524a-11ea-99ca-da5e3c089f8c.png)|

IconLink: allow icon and text to be included in Link

---

package.json

Just follow on I missed to do a tag release.

bump to version 1.1.92

---

package.json
src/components/index.d.ts
src/nora/components/Attributes.css
src/nora/components/NoraButton/NoraButton.js
src/nora/components/NoraButton/NoraButton.md
src/nora/components/NoraButton/NoraButton.module.scss
src/nora/components/NoraButton/NoraButton.test.js
src/nora/components/NoraButton/NoraButtonExample.module.scss
src/nora/components/NoraButton/__snapshots__/NoraButton.test.js.snap
src/nora/components/Tag/Tag.md

- [Asana Task](https://app.asana.com/0/1150068311310825/1162925575699393)
- Creates a default EDS Nora Button that allows for customization (given that lengths margin/padding etc may differ)
- NOTE: DO NOT MERGE until it is approved AND a tag is added to the PR. 
-

EDS: Nora Button

---

package.json
src/components/index.js
src/components/index.tests.tsx
src/nora/components/NoraButton/NoraButton.module.scss
src/nora/components/NoraButton/index.js
src/nora/components/index.js

- After merging 265 I realized we had some things missing from there in terms of exports and what not. Also, when we changed IconLink prop, we never updated the type defs accordingly
- https://github.com/getethos/ethos-design-system/pull/265

Nora button and icon link followup

---

package.json
src/components/Animation.scss
src/components/design-system.css
src/nora/components/IconLink/IconLink.md
src/nora/components/IconLink/IconLink.module.scss
stats.json

… Tom's designs
- [Asana Task](https://app.asana.com/0/1150068311310825/1162754458113945/f)
- Active Icon Links
- Colored states e.g. Error, Waived, Completed keep the icon color even in "Active" state, just the text gets black/bolded
Completed
Error
Waived

Active Icon Links

---

package.json
src/components/index.d.ts
src/nora/components/NoraCheckboxInput/NoraCheckboxInput.js

- Add `data-tid` and boolean `initialValue`. Noticed these errors when consuming this component in Nora. 
- No, updates/fixes for existing component
-

NoraCheckboxInput: Add data-tid and boolean initialValue

---

package.json
src/components/fa.js
src/nora/components/NoraCheckboxInput/NoraCheckboxInput.md

- https://app.asana.com/0/1150068311310825/1165337465443585
- Adding an icon for Nora designs
-

Add cancel/delete icon

---

src/components/UniversalNavbar/NavLink.js
src/components/UniversalNavbar/UniversalNavbar.d.ts
src/components/UniversalNavbar/UniversalNavbar.js
src/components/UniversalNavbar/UniversalNavbar.module.scss
src/components/UniversalNavbar/__snapshots__/UniversalNavbar.test.js.snap
src/components/UniversalNavbar/constants.js
src/components/UniversalNavbarExpanded/SampleContent.js
src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.d.ts
src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.js
src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.test.js
src/components/UniversalNavbarExpanded/__snapshots__/UniversalNavbarExpanded.test.js.snap
src/components/index.d.ts
src/components/index.tests.tsx

- declaration files UniversalNavbar and UniversalNavbarExpanded
- UniversalNavbar to use functional component and using hooks
- 404 page PR: https://github.com/getethos/cms/pull/2782 because it is going to be written in Typescript

Change types for UniversalNavbar

---

package.json
src/components/CheckboxInput/CheckboxInput.js
src/components/CheckboxInput/CheckboxInput.test.js
src/components/CheckboxInput/__snapshots__/CheckboxInput.test.js.snap
src/components/Form/Form.js
src/components/index.d.ts
src/nora/components/NoraCheckboxInput/NoraCheckboxInput.js
src/nora/components/NoraCheckboxInput/NoraCheckboxInput.md

- [Asana Task](https://app.asana.com/0/1150068311310825/1162798638929455/f)
- Adds capability to dynamically set `checked` on checkboxes. Blocked the MedExam Layout + Accordion Implementation effort, so this is related to that Asana task.
- https://github.com/getethos/ethos/pull/2514 pulls this in

NoraCheckboxInput updates

---

package.json
src/components/Drawer/Drawer.js
src/components/index.d.ts
src/components/index.tests.tsx
src/nora/components/NoraDrawer/NoraDrawer.js
src/nora/components/NoraDrawer/NoraDrawer.md
src/nora/components/NoraDrawer/__snapshots__/NoraDrawer.test.js.snap

- [Asana Task](https://app.asana.com/0/1150068311310825/1165656047057585/f)
- MedExam Layout + Accordion Sticky Footer Button
(https://eds.ethoslabs.io/#/Guidelines?id=section-contribute) guide?
- https://github.com/getethos/ethos/pull/2528
See the monorepo PR

Noradrawer classname

---

package.json
src/components/EmailInput/__snapshots__/EmailInput.test.js.snap
src/components/PasswordInput/__snapshots__/PasswordInput.test.js.snap
src/components/TextAreaInput/TextAreaInput.js
src/components/TextAreaInput/__snapshots__/TextAreaInput.test.js.snap
src/components/TextInput/TextInput.js
src/components/TextInput/__snapshots__/TextInput.test.js.snap

- [Asana Task](https://app.asana.com/0/1138529592199337/1165205282200433)

Fix text input copy paste duplication

---

package.json
src/nora/components/IconLink/IconLink.js
src/nora/components/IconLink/IconLink.test.js

- https://app.asana.com/0/1150068311310825/1166785036458321
- https://github.com/getethos/ethos/pull/2599

Make onClick optional in IconLink

---

package.json
src/components/Drawer/Drawer.js
src/components/Drawer/Drawer.md
src/components/Snackbar/Snackbar.test.js
src/components/Snackbar/__snapshots__/Snackbar.test.js.snap
src/components/index.d.ts
src/nora/components/NoraDrawer/NoraDrawer.js
src/nora/components/NoraSnackbar/NoraSnackbar.test.js
src/nora/components/NoraSnackbar/__snapshots__/NoraSnackbar.test.js.snap

- [Asana Task](https://app.asana.com/0/1150068311310825/1166816227369121/f)
- Locking Drawer (ability to pass in `lock: {true}` to opt out of click outside / escape closing drawer

Lock drawer

---

package.json
src/components/FlexGrid/FlexGrid.js
src/components/FlexGrid/__snapshots__/FlexGrid.test.js.snap
src/components/FlexGrid/classNames.js
src/components/FlexGrid/flexboxgrid2-customized.css
src/components/FlexGrid/flexboxgrid2-customized.scss
webpack.config.js
yarn.lock

- [Asana Task](https://app.asana.com/0/1150068311310825/1167426142339121/f)
- Refactors FlexGrid to remove all magic gutters!
-
Two things to note:
1. No margins on top grid
2. No padding on columns in second grid

Flexgrid css diverge

---

package.json
src/components/fa.js

Add missing Nora icon

---

package.json
src/nora/components/NoraTextAreaInput/NoraTextAreaInput.js
src/nora/components/NoraTextAreaInput/__snapshots__/NoraTextAreaInput.test.js.snap

This is for getting the decline flow's components connected to eds form engine. This is the nora textarea one.
- https://github.com/getethos/ethos/pull/2879/files

connects the nora textarea to the form engine

---

README.md

- update Readme to make fontawesome setup more straightforward for first-time developers of this repo
-

update README to include link to instructions for Font Awesome dev setup

---

src/components/AsyncTypeahead/AsyncTypeahead.md
src/components/AsyncTypeahead/AsyncTypeahead.module.scss
src/components/Grid/Grid.md
src/components/Grid/Grid.module.scss
src/components/Grid/Row.module.scss
src/components/Select/Select.md
src/components/Select/Select.module.scss

- [Asana Task](https://app.asana.com/0/1150068311310825/1171482375244427/f)
- Fix Grids css fallback properties
- Adds fallback properties to Select and AsyncTypeahead so we can skin.
Grid:
Select (preserving defaults):
AsyncTypeahead (preserving defaults):

Fix Grids css fallback propertie and adds fallback properties to Select and AsyncTypeahead

---

src/components/Button/Button.js
src/components/Button/Button.md
src/components/Button/Button.test.js
src/components/Button/__snapshots__/Button.test.js.snap
src/components/index.d.ts

- [Asana Task](https://app.asana.com/0/1152139407849001/1167233174456285)
- 
-
- added section to Styleguide

change children prop type in Button from string to ReactNode

---

package.json
src/components/Popover/Option.js
src/components/Popover/Options.js
src/components/index.d.ts
src/components/index.tests.tsx
src/nora/components/KabobMenu/KabobExample.module.scss
src/nora/components/KabobMenu/KabobMenu.js
src/nora/components/KabobMenu/KabobMenu.module.scss
src/nora/components/KabobMenu/KabobMenuContainer.js

This is a part of https://app.asana.com/0/1150068311310825/1170387956248380/f
I just used the dashboard's list view to test this out (but it won't actually go there when we use it -- it's for some of our detail view's decision tables). But:
I still have some work to do on making this fully work with the data grid, but I have that follow up tracked on the Asana. I'd like to iterate so I'm looking to merge what I have here if possible.

Nora kabob types version bump etc

---

package.json
src/components/Media/Media.scss
src/components/fa.js

mobile layout icons and updated breakpoints

---

package.json
src/components/fa.js

- [Asana Task](https://app.asana.com/0/1150068311310825/1177025445395809/f)
-
-

Add sign out icon for Nora

---

package.json
src/nora/components/Tag/Tag.js
src/nora/components/Tag/Tag.module.scss

- [Asana Task](https://app.asana.com/0/1150068311310825/1176688385701580/f)
-
-

Add neutral tag style

---

package.json

Move cloudinary_core from devDependency to dependecy in package.json

---

package.json
src/components/BirthdateInput/__snapshots__/BirthdateInput.test.js.snap
src/components/Button/Button.module.scss
src/components/ButtonSelectGroup/__snapshots__/ButtonSelectGroup.test.js.snap
src/components/DateInput/__snapshots__/DateInput.test.js.snap
src/components/EmailInput/__snapshots__/EmailInput.test.js.snap
src/components/InputLabel.js
src/components/NumberInput/NumberInput.js
src/components/NumberInput/__snapshots__/NumberInput.test.js.snap
src/components/PasswordInput/__snapshots__/PasswordInput.test.js.snap
src/components/RadioButtons/__snapshots__/RadioButtons.spec.js.snap
src/components/TextAreaInput/__snapshots__/TextAreaInput.test.js.snap
src/components/TextInput/__snapshots__/TextInput.test.js.snap
src/components/TextMaskedInput/TextMaskedInput.js
src/components/ZipInput/__snapshots__/ZipInput.test.js.snap

- [Asana Task](https://app.asana.com/0/1147552137426708/1188393054373587)
- 
-

pass placeholderChar prop to masked input; minor styling tweaks

---

package.json
src/components/index.d.ts

- derp; didn't notice this until I bumped eds in monorepo
-

update type props for placeholderChar

---

package.json
src/components/BirthdateInput/BirthdateInput.js
src/components/ButtonSelectGroup/ButtonSelectGroup.js
src/components/CheckboxInput/CheckboxInput.js
src/components/DateInput/DateInput.js
src/components/EmailInput/EmailInput.js
src/components/InputLabel.js
src/components/NumberInput/NumberInput.js
src/components/RadioButtons/RadioButtons.js
src/components/TextAreaInput/TextAreaInput.js
src/components/TextInput/TextInput.js
src/components/TextMaskedInput/TextMaskedInput.js
src/components/TypeBase/TypeBase.js
src/components/TypeBase/TypeBase.module.scss
src/components/ZipInput/ZipInput.js
src/components/index.d.ts
src/nora/components/NoraTextInput/NoraTextInput.js

- [Asana Task](https://app.asana.com/0/1147552137426708/1189411290380233/f)
- Adds prop to capitalize label

Label capitalize

---

package.json
src/components/Tooltip/Tooltip.js

- [Asana Task](https://app.asana.com/0/1147552137426708/1128442970730787/f)
- [Damn you safari!](https://stackoverflow.com/questions/35719526/safari-ignore-window-matchmedia)

Tooltip safari fix

---

package.json
src/components/Select/Select.js
src/components/index.d.ts

- Add ability to disable uppercasing to select
- Add missing argument in onChange handler

Select fixes

---

package.json
src/components/BirthdateInput/__snapshots__/BirthdateInput.test.js.snap
src/components/DateInput/DateInput.js
src/components/DateInput/__snapshots__/DateInput.test.js.snap
src/components/NumberInput/NumberInput.js
src/components/Select/Select.module.scss
src/components/ZipInput/ZipInput.js
src/components/index.d.ts

- Add missing prop type to TextMaskedInput `formChangeHandler` 
- Expose props `guide` and `keepCharPositions`
- Fix minor Select sizing

Various fixes

---

package.json
src/components/Select/Select.module.scss

- Not sure why Rob added this. react-select by default doesn't do this and seems to work fine. Fixes [Issue](https://app.asana.com/0/1147552137426708/1190441581347540/f)

Select - remove overflow visible

---

package.json
src/components/BirthdateInput/__snapshots__/BirthdateInput.test.js.snap
src/components/CheckboxInput/CheckboxInput.module.scss
src/components/DateInput/DateInput.js
src/components/DateInput/__snapshots__/DateInput.test.js.snap
src/components/NumberInput/__snapshots__/NumberInput.test.js.snap
src/components/TextMaskedInput/TextMaskedInput.js
src/components/ZipInput/__snapshots__/ZipInput.test.js.snap
src/components/index.d.ts

- [Asana Task](https://app.asana.com/0/1147552137426708/1190266271588105/f)
- also tweaked checkbox height by 2px

Date input paste fix

---

package.json
src/components/fa.js

- [Asana Task](https://app.asana.com/0/1188578271286017/1195721610774667/f)
-
-

Add sync icon to Nora

---

package.json
src/components/ButtonSelectGroup/ButtonGroup.module.scss

- [Asana Task](https://app.asana.com/0/1127465823644688/1190680049929889)
- Small change as part of the above ticket.
-

SI: Change ButtonSelect margin

---

package.json

- Forgot to bump version https://github.com/getethos/ethos-design-system/pull/369
-
-

Bump new version for #369

---

package.json
src/components/TextAreaInput/TextAreaInput.js

- Fixing a prop type that was throwing a console error
**Before:**
**After:**

[Bug Fix] Fix prop types for TextAreaInput

---

package.json
src/components/fa.js

added fabell icon

---

package.json
src/validators/DateInputValidator.d.ts
src/validators/DateInputValidator.js
src/validators/EmailValidator.d.ts
src/validators/EmailValidator.js
src/validators/ZipInputValidator.d.ts
src/validators/ZipInputValidator.js

- Based on design feedback from Matt, removes all the periods from validation messages

Remove periods from messages

---

package.json
src/components/Select/Select.js

- unable to `mount` <Select /> because onBlur was being used before it was initialized

Change initialization order of variables in select

---

package.json
src/components/Button/Button.js
src/components/Button/Button.md
src/components/Button/__snapshots__/Button.test.js.snap
src/components/ButtonSelectGroup/__snapshots__/ButtonSelectGroup.test.js.snap
src/hooks/useDebounce.js
src/hooks/useDebounce.test.js

- [Asana Task](https://app.asana.com/0/1116481661798430/1200056096864969)
-
-

Add debounce to buttons

---

package.json
src/components/Button/Button.js

Default button debounce to zero

---

.github/workflows/deploy.yml
nginx.Dockerfile

Build a Docker image with nginx on every deploy + push to ECR.
- [Asana Task](https://app.asana.com/0/1151126143260097/1200229414343533/f)

Build an nginx Docker image part of normal deploy

---

package.json
src/components/BirthdateInput/BirthdateInput.js
src/components/ButtonSelectGroup/ButtonSelectGroup.js
src/components/DateInput/DateInput.js
src/components/TextMaskedInput/TextMaskedInput.js
src/components/index.d.ts

allows passing thru labelColor,labelWeight,labelClasses
tightens up BirthdateInput code, just for kicks

floating header extension 2

---

package.json
src/components/EmailInput/__snapshots__/EmailInput.test.js.snap
src/components/PasswordInput/__snapshots__/PasswordInput.test.js.snap
src/components/TextAreaInput/TextAreaInput.module.scss
src/components/TextInput/TextInput.js
src/components/TextInput/__snapshots__/TextInput.test.js.snap

This should round out all the TextInput changes

stylable inputs

---

package.json
src/components/index.d.ts

make onClick optinal in d.ts file for RadioButton

---

README.md
package.json
src/components/Button/Button.js
src/components/Button/Button.md
src/components/Button/Button.module.scss
src/components/UniversalNavbar/__snapshots__/UniversalNavbar.test.js.snap

refresh icon button

---

package.json
src/components/Button/Button.js
src/components/Button/Button.module.scss
src/components/index.d.ts

To fix a bug with icon alignment in the refreshIcon variant.

Button refreshIconInner class

---

PULL_REQUEST_TEMPLATE.md
package.json
src/components/EmailInput/EmailInput.js
src/components/EmailInput/EmailInput.md
src/components/TextInput/TextInput.js
src/components/index.d.ts

- https://github.com/getethos/cms/commit/1cee584bc6a43f69a5563954bc581823597aa7c7

more flexible EmailInput

---

package.json
src/components/UniversalNavbarExpanded/MobileNav/MobileNav.js
src/components/UniversalNavbarExpanded/MobileNav/MobileNav.module.scss
src/components/UniversalNavbarExpanded/SampleContent.js
src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.d.ts
src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.js
src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.md
src/components/UniversalNavbarExpanded/__snapshots__/UniversalNavbarExpanded.test.js.snap

- https://github.com/getethos/cms/pull/4868

Add new singleCta variation of UniversalExpandedNavbar

---

package.json
src/validators/NumberInputValidator.d.ts
src/validators/NumberInputValidator.js
src/validators/NumberInputValidator.test.js

https://user-images.githubusercontent.com/84357906/146285367-fa4d515a-42c2-4b02-9a45-d536bd5aaae9.mov

Add number range validator

---

src/components/Tooltip/Tooltip.module.scss

Tooltip close button position

---

package.json
src/components/Button/Button.js
src/components/Button/Button.md
src/components/Button/Button.module.scss
src/components/Button/Button.test.js
src/components/Button/__snapshots__/Button.test.js.snap
src/components/Colors.scss
src/components/design-system.css
src/components/index.d.ts
stats.json

FINAL nominal button and disabled state
Hover background-color visible in middle image

add Salamander Button;

---

package.json
src/components/UniversalNavbarExpanded/CtaButton.js
src/components/UniversalNavbarExpanded/MobileNav/MobileNav.js
src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.d.ts
src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.js
src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.md
src/components/UniversalNavbarExpanded/__snapshots__/UniversalNavbarExpanded.test.js.snap

black outline cta in navbar

---

package.json
src/components/Modal/Modal.js
src/components/Modal/Modal.module.scss
src/components/Modal/__snapshots__/Modal.test.js.snap
src/components/Variables.scss

https://user-images.githubusercontent.com/84357906/183788908-f17de6df-2595-4b90-aabb-b531acf1eed8.mov

Add un-clickable backdrop to Modal

---

package.json

Update Package.json version number

---

package.json
src/components/Tooltip/Tooltip.js

Adding the capability to track views on the Tooltip

add trackingFunction to tooltip

---

package.json

-
- Accidentally created a tag on a slightly older version of master

Create Release v1.2.38

---

package.json
src/components/Images/Images.js
src/components/Images/__snapshots__/Images.spec.js.snap
src/components/index.d.ts
yarn.lock

- Mostly just read the documentation and made sure the images still looked good 😄

[GC-1587] Update Cloudinary Package

---

package.json

Update Version v1.3.11

---

package.json

- Treeshaking this repository will allow consuming repositories to remove unused code and import _only_ the things they need.
- In the CMS this reduces EDS' footprint more than 66%, from 75k to 38k gzipped.
before
after

[GC-1745] EDS Treeshaking

---

package.json
src/components/UniversalNavbar/FancyAnimatedLogo.scss
src/components/UniversalNavbar/TransformingBurgerButton/TransformingBurgerButton.module.scss
src/components/design-system.css
stats.json

- https://github.com/getethos/cms/pull/6952
- By animating "all" properties, this can have unintended consequences when applying `visibility: hidden`. Let's only animate the properties we care about.
before
https://user-images.githubusercontent.com/33670137/216189713-2cf71a2a-bcf4-4aea-986e-62e93412728b.mov
after
https://user-images.githubusercontent.com/33670137/216189663-bc0e0bb1-3547-43d3-b337-41dc5cfcc39f.mov

GC-1763 Universal Navbar animation tweak

---

package.json
src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.module.scss

Nav-bar follow-ups:
- Animate nav bar border-bottom
- White background on hover
-
https://user-images.githubusercontent.com/96451437/221056273-4f6d26b8-91ea-4b02-b380-a13f4cbced4f.mov
d extra notes:

[GC-1932] Nav bar follow ups

---

package.json

Bump version to v1.3.25

---

package.json
src/components/UniversalNavbar/assets/icons.js

Updated icon sizes for navbars.
-

[GC-2577] icons update

---

package.json
src/components/TypeBase/TypeBase.scss
src/components/UniversalNavbarExpanded/MobileNav/MobileNav.js
src/components/UniversalNavbarExpanded/MobileNav/MobileNav.module.scss
src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.js
src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.module.scss
src/components/UniversalNavbarExpanded/__snapshots__/UniversalNavbarExpanded.test.js.snap

GC-2393 forbes logo cms next

---

package.json
src/components/UniversalNavbarExpanded/MobileNav/MobileNav.js
src/components/UniversalNavbarExpanded/MobileNav/MobileNav.module.scss
src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.js
src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.module.scss
src/components/UniversalNavbarExpanded/__snapshots__/UniversalNavbarExpanded.test.js.snap

https://drive.google.com/drive/folders/1nKfAtEBzLlLFfxf6WVfZrJZXx906QrJZ?usp=sharing

GC-2393 forbes logo

---

src/components/UniversalNavbarExpanded/MobileNav/MobileNav.module.scss

-https://github.com/getethos/cms-next/pull/637

feat: add border on mobile transparent background

---

src/components/UniversalNavbarExpanded/MobileNav/MobileNav.js
src/components/UniversalNavbarExpanded/SampleContent.js
src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.md

Does not render CTA button if partnerLogo for mobile is present
[Jira Task](https://ethoslife.atlassian.net/browse/GC-3278)
**Before**
**After**

[GC-3278]: Update Forbes Advisor mobile header

---

package.json

Version 1.3.30 already existed and I pushed up a tag manually for 1.3.31

Version Bump to v1.3.32

---

.github/workflows/deploy.yml

Use node 20 in deploy workflow

---

package.json

Upgrade to 1.3.35

---

package.json
src/components/TextInput/TextInput.js

feat: append maxLength on text input

---

src/components/UniversalNavbarExpanded/UniversalNavbarExpanded.js

feat: additional prop for independant partnerLogo [CEQ2-1055]

---

package.json

release: v1.3.40
